# example netlify.toml
[build]
  command = "astro build"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["esbuild", "http-status-codes"]
  included_files = ["astro.i18n.config.ts"]
